# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app
# Install build dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*
# Copy and install dependencies
COPY requirements-lock.txt requirements.txt ./
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements-lock.txt
# Copy application code
COPY . .
# Default command for stdio server
CMD ["python", "mcp_server.py"]
