# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from Python 3.10 slim to satisfy MCP requirements
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements-lock.txt requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements-lock.txt

# Copy application source code
COPY . .

# Default entrypoint to run the MCP server via stdio
ENTRYPOINT ["python", "mcp_server.py"]
